INSERT INTO animals (name, speed, avatar_url) VALUES ('Zebra', 0.9, '/zebra.png');
INSERT INTO animals (name, speed, avatar_url) VALUES ('Llama', 0.2, '/llama.png');
INSERT INTO animals (name, speed, avatar_url) VALUES ('Owl', 0.8, '/owl.png');
INSERT INTO animals (name, speed, avatar_url) VALUES ('Dove', 0.55, '/dove.png');
INSERT INTO animals (name, speed, avatar_url) VALUES ('Shark', 1, '/shark.png');
INSERT INTO animals (name, speed, avatar_url) VALUES ('Octopus', 0.8, '/octopus.png');
INSERT INTO animals (name, speed, avatar_url) VALUES ('Phoenix', 2, '/phoenix.png');
INSERT INTO animals (name, speed, avatar_url) VALUES ('Unicorn', 1, '/unicorn.png');
INSERT INTO animals (name, speed, avatar_url) VALUES ('Dragon', 1.7, '/dragon.png');