INSERT INTO animals (name, speed, avatar_url) VALUES ('Zebra', 0.09, '/zebra.png');
INSERT INTO animals (name, speed, avatar_url) VALUES ('Llama', 0.02, '/llama.png');
INSERT INTO animals (name, speed, avatar_url) VALUES ('Owl', 0.03, '/owl.png');
INSERT INTO animals (name, speed, avatar_url) VALUES ('Dove', 0.05, '/dove.png');
INSERT INTO animals (name, speed, avatar_url) VALUES ('Shark', 0.08, '/shark.png');
INSERT INTO animals (name, speed, avatar_url) VALUES ('Octopus', 0.04, '/octopus.png');
INSERT INTO animals (name, speed, avatar_url) VALUES ('Phoenix', 1, '/phoenix.png');
INSERT INTO animals (name, speed, avatar_url) VALUES ('Unicorn', 0.2, '/unicorn.png');
INSERT INTO animals (name, speed, avatar_url) VALUES ('Dragon', 0.5, '/dragon.png');