INSERT INTO animals (name, speed, avatar_url) VALUES ('Zebra', 65, '/zebra.png');
INSERT INTO animals (name, speed, avatar_url) VALUES ('Llama', 35, '/llama.png');
INSERT INTO animals (name, speed, avatar_url) VALUES ('Owl', 400, '/owl.png');
INSERT INTO animals (name, speed, avatar_url) VALUES ('Dove', 88, '/dove.png');
INSERT INTO animals (name, speed, avatar_url) VALUES ('Shark', 50, '/shark.png');
INSERT INTO animals (name, speed, avatar_url) VALUES ('Octopus', 40, '/octopus.png');
INSERT INTO animals (name, speed, avatar_url) VALUES ('Phoenix', 800, '/phoenix.png');
INSERT INTO animals (name, speed, avatar_url) VALUES ('Unicorn', 900, '/unicorn.png');
INSERT INTO animals (name, speed, avatar_url) VALUES ('Dragon', 1000, '/dragon.png');