DROP TABLE IF EXISTS parents CASCADE;

CREATE TABLE parents (
  id SERIAL PRIMARY KEY NOT NULL,
  username VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  avatar_url text NOT NULL,
  password VARCHAR(255) NOT NULL
);